### ISSUE TITLE
Thank you! linux soon?

### ISSUE THREAD

**Issue by j2l** [ksami/QRemeshify#10]
Just wanted to thank you!
Hope to test it soon, please let me know when linux is tested, or if you have an ETA :smiley: 
Have a great day!

**Comment by ksami** [comment]
There's a linux build available, had ~100 downloads so far but I haven't had any feedback about it. Would appreciate it if you try it out to let me know how it goes https://github.com/ksami/QRemeshify/releases/download/1.1.0/QRemeshify-1.1.0-linux.zip

**Comment by j2l** [comment]
Aah, didn't see it, sorry :smile: 
Here's my review:
With default settings, it is working great!
Both on Blender 4 and 3.6. No crash.
![image](https://github.com/user-attachments/assets/407fa235-a733-459d-9f5a-0973c663e108)
to
![image](https://github.com/user-attachments/assets/6cdc99bb-3e2c-474e-aa85-55761893131d)

I expected density = 0.1 to be less dense, the opposite oft he result I got.

It doesn't detect symmetry:
![image](https://github.com/user-attachments/assets/f06b2c15-18a3-420b-869c-4f5d9d99c414)

Wonderful add-on! Thank you very much for sharing this gem!
