### ISSUE TITLE
Could you also build this for macos-x64 please?

### ISSUE THREAD

**Issue by vigilantesculpting** [ksami/QRemeshify#11]
It looks like the macos build only has support for arm64.

Setup:
Intel-based Mac with Blender 4.2.1 installed

Steps to reproduce problem:
1. Download QRemeshify 1.1.0 for macos
2. Add plugin to Blender 

Result:
Blender reports error: Platform (macos-x64) is not one of windows-x64, macos-arm64 or linux-x64)

**Comment by ksami** [comment]
The underlying library https://github.com/cgg-bern/quadwild-bimdf only released builds for arm64 and I don't know enough to make a new build of my own

**Comment by mheistermann** [comment]
Hi, quadwild-bimdf author here :-)

It's possible that this a small cmake setting when building the library suffices, have a look here:
https://github.com/cgg-bern/quadwild-bimdf/blob/main/.github/workflows/build.yaml#L89
The flag `-DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"` is supposed to build a "fat" binary that contains code for both architectures.
To be honest, I think I never actually tested on x86_64 mac, but maybe @vigilantesculpting can test if the binaries from the quadwild-bimdf releases work:
https://github.com/cgg-bern/quadwild-bimdf/tags

(They won't work directly in QRemeshify, which needs a library build, but being able to run those would give a strong hint for it to work just as well for a library).

Hope this helps :-)

**Comment by ksami** [comment]
Well I clearly don't know enough about C++ then, I assumed because the Github build agent was arm64 that it would only produce arm64 builds. QRemeshify should work then since it was built in the same way.

Open the zip file, look for `QRemeshify/blender_manifest.toml`, find this line https://github.com/ksami/QRemeshify/blob/main/QRemeshify/blender_manifest.toml#L37 and add `macos-x64` to the list to try it out

**Comment by vigilantesculpting** [comment]
I can give this a go on my machine today. Will let you know what I find.

**Comment by vigilantesculpting** [comment]
The suggested fix works for me.

First, I tried running the Quadwild binary directly from the commandline, and this worked - it did not complain about being arm64 only.

Next, I unzipped the QRemeshify zipfile, modified the blender_manifest.xml file, then re-zipped the QRemeshify zipfile and installed it in Blender.

I then successfully remeshed Suzanne.

Thanks!
