### ISSUE TITLE
Preprocess issue

### ISSUE THREAD

**Issue by mifth** [ksami/QRemeshify#12]
Hi, I've noticed that the Preprocess affects a resolution of a mesh (an amount of polygons).

![image](https://github.com/user-attachments/assets/081d53c1-d213-4727-b4e9-86e8177d01d8)

![image](https://github.com/user-attachments/assets/8cf6f110-9085-43f8-94aa-6e3420ba8744)

**Comment by ksami** [comment]
Yes the `Preprocess` option runs Quadwild's built-in decimation, triangulation and fixes as stated here https://github.com/ksami/QRemeshify?tab=readme-ov-file#settings

**Comment by mifth** [comment]
Thanks a lot for your answer. I understand about mesh optimisations. But if a mesh has the same size then the resolution will be the same as far as I know.

**Comment by mifth** [comment]
It seems the resolution depends on mesh density. I'm closing the issue.

![image](https://github.com/user-attachments/assets/b6db8dff-82a0-477e-9002-8126e91cdd32)

![image](https://github.com/user-attachments/assets/7eb874fb-619f-4f57-aa07-a00993d44fe1)
