### ISSUE TITLE
Error when running model

### ISSUE THREAD

**Issue by Lindenrb** [ksami/QRemeshify#3]
Hi, 

For very simple objects it seems to be working for me, but when trying to run on a slightly more complex model (100k triangles) I am getting the following error:

Any ideas what I might be doing wrong. Running Blender 4.2.2 LTS on Windows 10

```
Python: Traceback (most recent call last):
  File "C:\Users\$$$$$$\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\qremeshify\lib\__init__.py", line 148, in quadrangulate
    return self.quadpatches.quadPatches(mesh_path_c, byref(params), scaleFact, fixedChartClusters, enableSmoothing)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: exception: access violation reading 0x000001D201CD0070

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\$$$$$$\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\qremeshify\lib\__init__.py", line 150, in quadrangulate
    raise QWException("quadPatches failed") from e
bl_ext.user_default.qremeshify.lib.QWException: quadPatches failed
```
Username replaced with $$$$$$

**Comment by ksami** [comment]
I've gotten that error before when there's loose geometry, try separating those into individual objects. Might also want to try decimating the model manually to test before running it again on the full 100k tris.

You can find more tips here https://github.com/ksami/QRemeshify?tab=readme-ov-file#tips

**Comment by Lindenrb** [comment]
Thanks, seems the model is a little complex with overlapping (awful) topology. I'm trying to retopo a game rip mesh which is why the topology is so bad.
Seems to run OK when I break the model down, thanks for getting back to me

**Comment by Lindenrb** [comment]
How about this error? I've split the model up into smaller pieces, and then have used mark sharp to try and line the edges and flow of topology I wanted. Have I exceeded the number of sharp edges it can handle?
Can understand if you haven't seen this one before
`
Python: Traceback (most recent call last):
  File "C:\Users\$$$$$$\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\qremeshify\operator.py", line 71, in execute
    num_sharp_features = exporter.export_sharp_features(bm, qw.sharp_path, props.sharpAngle)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\$$$$$$\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\qremeshify\util\exporter.py", line 17, in export_sharp_features
    face_index = edge.link_faces[0].index
                 ~~~~~~~~~~~~~~~^^^
IndexError: BMElemSeq[index]: index 0 out of range
`

**Comment by ksami** [comment]
Yeah I haven't seen this one before. I don't think there's a limit to the number of sharp edges. My guess is there are edges that are not part of any face?

**Comment by ksami** [comment]
Please reopen if there's still an issue
