### ISSUE TITLE
How can I resolve this error?

### ISSUE THREAD

**Issue by ogatahiroyuki** [ksami/QRemeshify#9]
When I ran it, I got the following error:

FileNotFoundError: Could not find module C:\Users\xxxx\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\qremeshify\lib\lib_quadwild.dll' (or one of its dependecies).Try using the full path with constructor syntax.

**Comment by ksami** [comment]
Seems like something went wrong during installation.

Try re-installing the extension, or manually extract the zip file and move `lib_quadwild.dll` found in `QRemeshify\lib` to `C:\Users\xxxx\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\qremeshify\lib`

**Comment by ogatahiroyuki** [comment]
Thank you.
 I thought the same thing, so I tried unzipping it manually, but lib_quadwild.dll was not present in the unzipped lib.

**Comment by ksami** [comment]
That's strange, where did you download the zip from?

Could you try again with https://github.com/ksami/QRemeshify/releases/download/1.1.0/QRemeshify-1.1.0-windows.zip

**Comment by ogatahiroyuki** [comment]
Thanks.
I cloned it from Git and unzipped it and it wasn't there,
but I downloaded it from the link you provided and it was there.
It worked too. Thanks
